name = "prospector"
main = "src/index.ts"
compatibility_date = "2022-10-24"
node_compat = true

kv_namespaces = [
  { binding = "USER_STATE", id = "e817b46da5a34439b2e82e31ffbe909e" }
]

[vars]
PUBLIC_KEY = "c2c69b45c68051dcf949ab9fe21789d4803b9f68e064519cd2db5dc1e306bc62"
